import "./globals.css";

import Header from "../components/Header"; // Import the Header component
import Footer from "../components/Footer"; // Import the Footer component

export const metadata = {
  title: "PantryPie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Sora:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="flex flex-col bg-yellow-50">
        <Header />
        <main className="flex flex-1 flex-col bg-yellow-50">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
