import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

import Header from "../components/Header"; // Import the Header component
import Footer from "../components/Footer"; // Import the Footer component

export const metadata = {
  title: "PantryPie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        className="flex flex-col bg-yellow-50"
        style={{ fontFamily: inter }}
      >
        <Header />
        <main className="flex flex-1 flex-col bg-yellow-50">{children}</main>
        <Footer /> 
      </body>
    </html>
  );
}
